#!/usr/bin/perl

# in case we get executed (not sourced) as a shell program
eval 'exec perl -S $0 ${1+"@"}'
    if $running_under_some_shell;

BEGIN {
    use strict;
    use warnings;
    my $here = $0; $here =~ s{/[^/]*$}{};
    if ($here =~ s{^\.}{}) {
	chomp(my $cwd = `pwd`);
	$here = "/$here" if $here;
	$here = "$cwd$here";
    }
    unshift @INC, "$here/lib" unless $here =~ m{^/usr/bin};
}

=head1 NAME

xdg-places - an XDG compliant places menu

=head1 SYNOPSIS

 xdg-places [OPTIONS]

=head1 DESCRIPTION

B<xdg-places> provides an XDG compliant system tray places menu.  The
tool is capable of generating XDG places menus for a number of 

=cut

